// Suppress Google Maps tile 503 errors in console
window.addEventListener('error',e=>{const msg=String(e?.message||'');const url=e?.filename||'';if((msg.includes('503')||msg.includes('Offline'))&&(url.includes('mt')||url.includes('google'))){e.preventDefault();return true}},true);
// Intercept failed tile loads
const originalFetch=window.fetch;window.fetch=function(...args){const url=String(args[0]||'');if(url.includes('mt1.google.com')||url.includes('mt2.google.com')||url.includes('mt3.google.com')){return originalFetch.apply(this,args).catch(e=>{console.debug('[Map] Google tile load failed (expected in offline mode)',url);return new Response(new Blob(['GIF89a'],{type:'image/gif'}),{status:200,statusText:'OK'})})}}; 

function useTouchComfortMode(){return isMobileCollector()||window.matchMedia('(pointer: coarse)').matches}
function isPointLayer(layer){return layer instanceof L.Marker||layer instanceof L.CircleMarker||layer?.feature?.geometry?.type==='Point'}
function getDefaultFeatureStyle(){return{color:'#4caf50',weight:useTouchComfortMode()?5:3,fillOpacity:useTouchComfortMode()?.62:.55}}
function getSelectedFeatureStyle(){return{color:'#ff9800',weight:useTouchComfortMode()?7:3,fillOpacity:useTouchComfortMode()?.8:.7}}
function getUnselectedFeatureStyle(){return{color:'#2e7d32',weight:useTouchComfortMode()?4:2,fillOpacity:useTouchComfortMode()?.58:.5}}
function scrollCollectorPrimaryActionIntoView(){const saveButton=document.getElementById('save-entry-btn');if(saveButton&&window.innerWidth<900)requestAnimationFrame(()=>saveButton.scrollIntoView({behavior:'smooth',block:'nearest'}))}
function getSelectedGeometryAreaText(){if(!selectedPolygon||isPointLayer(selectedPolygon))return'Point';if(selectedPolygon.getLatLngs){const latlngs=selectedPolygon.getLatLngs();const ring=Array.isArray(latlngs?.[0])?latlngs[0]:latlngs;if(Array.isArray(ring)&&ring.length>=3){const area=L.GeometryUtil.geodesicArea(ring)/10000;if(Number.isFinite(area)&&area>0)return`${area.toFixed(2)} ha`}}return'Polygon'}
function updateMobileSaveFlowState(){const card=document.getElementById('save-flow-card');const title=document.getElementById('save-flow-title');const message=document.getElementById('save-flow-message');const chipRow=document.getElementById('save-flow-chip-row');if(!card||!title||!message||!chipRow)return;const chips=[];let nextTitle='Draw or select a shape';let nextMessage='Use the map tools, then tap the shape once to confirm it before saving.';const activeStepKey=getCollectorQuestionFlow(activeCollectorPrimaryModule)[currentCollectorWizardStep]||'';if(activeCollectorPrimaryModule==='livestock'){nextTitle='Livestock survey ready';nextMessage='No polygon is required for livestock. Complete the questionnaire pages, then submit the survey.';chips.push('No polygon needed')}else if(activeCollectorPrimaryModule==='crop'&&!currentCropPlan.length){nextTitle='Choose crops for this farm';nextMessage='Select one or more crops first. The app will then guide you to draw and fill each crop in sequence.'}else if(activeCollectorPrimaryModule==='crop'&&activeStepKey==='collector-draw-section'&&!selectedPolygon&&!editingEntryId){nextTitle='Draw current crop polygon';nextMessage='Use the map tools to draw the boundary for the current crop. When the polygon is ready, Next will unlock and the crop questionnaire will continue.'}else if(editingEntryId){nextTitle='Update this saved record';nextMessage=selectedPolygon?'The selected shape is linked to the record you are editing. Review the form, then update when ready.':'Review the saved record details, then update when ready.';chips.push('Editing record')}else if(selectedPolygon){nextTitle='Shape ready to save';nextMessage='You can save now, save and add another plot, or delete this drawing if it was a mistake.';chips.push(isPointLayer(selectedPolygon)?'Point ready':'Polygon ready');chips.push(getSelectedGeometryAreaText())}if(currentCropPlan.length&&activeCollectorPrimaryModule==='crop'){const activeCrop=currentCropPlan[currentCropPlanIndex];const nextCrop=currentCropPlan[currentCropPlanIndex+1];if(activeCrop)chips.push(`Current ${getCropPlanLabel(activeCrop)}`);if(nextCrop)chips.push(`Next ${getCropPlanLabel(nextCrop)}`)}if(activeFarmerPlotNumber>1)chips.push(`Next ${formatPlotLabel(activeFarmerPlotNumber)}`);const shouldShow=!!activeCollectorPrimaryModule||!!selectedPolygon||!!editingEntryId||activeFarmerPlotNumber>1;card.classList.toggle('visible',shouldShow);card.hidden=!shouldShow;title.textContent=nextTitle;message.textContent=nextMessage;chipRow.innerHTML=chips.map(text=>`<span class="save-flow-chip">${text}</span>`).join('');feather.replace()}
function focusCollectorSaveActions(){const actionStack=document.getElementById('save-action-stack');if(actionStack&&window.innerWidth<900)requestAnimationFrame(()=>actionStack.scrollIntoView({behavior:'smooth',block:'nearest'}))}
function setMapWorkflowBanner(mode='idle',title='',message=''){mapWorkflowMode=mode||'idle';const banner=document.getElementById('map-workflow-banner');const titleNode=document.getElementById('map-workflow-title');const messageNode=document.getElementById('map-workflow-message');if(!banner||!titleNode||!messageNode)return;if(!isMobileCollector()){banner.classList.remove('visible');return}const states={idle:{title:'Map ready',message:'Tap a draw tool to start a point or field boundary.'},drawingPolygon:{title:'Drawing field boundary',message:'Tap around the outside of the field, then tap the first point to finish.'},drawingPoint:{title:'Adding point',message:'Tap the map once to place the point, then continue with the form.'},selected:{title:'Shape selected',message:'The map shape is ready. Save it now or remove it if it was a mistake.'},editing:{title:'Editing saved shape',message:'Use the map tools only if you want to replace the saved geometry before updating.'},cleanup:{title:'Cleanup mode',message:'Tap Delete Mistake to remove the unsaved drawing, or draw again when ready.'}};const state=states[mode]||states.idle;titleNode.textContent=title||state.title;messageNode.textContent=message||state.message;banner.classList.add('visible');feather.replace()}
function setFieldReadinessStatus(id,message){const node=document.getElementById(id);if(node)node.textContent=message}
function setMbtilesGuidance(message){const node=document.getElementById('mbtiles-guidance');if(node)node.textContent=message}
function getCurrentLocationAccuracyMeters(){const raw=window.__collectorCurrentLocationAccuracyMeters;return Number.isFinite(Number(raw))?Number(raw):null}
function setGeofenceReadinessStatus(message){setFieldReadinessStatus('mobile-geofence-status',message)}
function describeCollectorGeofenceStatus(result){const distanceText=Number.isFinite(result?.distance)?` (${Math.round(result.distance)} m)`:'';switch(result?.state){case'inside-field':return'Inside field';case'near-boundary':return`Near boundary${distanceText}`;case'outside-field':return`Outside field${distanceText}`;case'gps-skipped':return'GPS unavailable, check skipped';default:return result?.message||'Ready to check at save'}}
function updateCollectorGeofenceStatus(result=null){if(result){setGeofenceReadinessStatus(describeCollectorGeofenceStatus(result));return}if(activeCollectorPrimaryModule==='livestock'){setGeofenceReadinessStatus('Not used for livestock');return}if(activeCollectorPrimaryModule!=='crop'){setGeofenceReadinessStatus('Applies to crop save only');return}if(!selectedPolygon&&!editingEntryId){setGeofenceReadinessStatus('Draw crop boundary to enable check');return}if(!currentLocationLatLng){setGeofenceReadinessStatus('GPS unavailable, check skipped');return}setGeofenceReadinessStatus('Ready to check at save')}
function describeMbtilesReadiness(){const dbg=window.__lastMBTilesDebug||null;if(!dbg?.stage)return{status:'Load MBTiles before going offline',guidance:'Load an MBTiles basemap before you leave network coverage. The map stays available in this browser session for field navigation and polygon capture.'};if(dbg.stage==='loaded'){const metadata=dbg.metadata||{};const name=metadata.name||dbg.fileName||'Offline basemap';const bounds=metadata.bounds?` Bounds: ${metadata.bounds}.`:'';const zoom=(metadata.minzoom!==undefined||metadata.maxzoom!==undefined)?` Zoom ${metadata.minzoom??'?'}-${metadata.maxzoom??'?'}.`:'';return{status:`Loaded ${describeMBTiles(metadata,dbg.fileName||name)}`,guidance:`${name} is ready for offline mapping in this browser session.${zoom}${bounds} Reload the file after a full browser reset if needed.`}}if(dbg.stage==='error')return{status:'Load failed',guidance:`MBTiles load failed: ${dbg.message||'Unknown error'}`};if(dbg.stage==='picker-open')return{status:'Choose an MBTiles file from device storage',guidance:'Select an .mbtiles, .sqlite, or .db basemap file from this device to prepare offline field mapping.'};return{status:'Preparing offline basemap',guidance:`MBTiles step: ${dbg.stage}. ${dbg.message||'Processing file...'}`}}
async function refreshFieldReadinessStatus(){const hasGps=!!currentLocationLatLng;const accuracyMeters=getCurrentLocationAccuracyMeters();const gpsMessage=hasGps?`Ready${Number.isFinite(accuracyMeters)?` (${Math.round(accuracyMeters)} m)`:''}`:'Waiting for location';const mbtilesStatus=describeMbtilesReadiness();setFieldReadinessStatus('mobile-gps-status',gpsMessage);setFieldReadinessStatus('mobile-photo-status',typeof isDesktopPhotoOptional==='function'&&isDesktopPhotoOptional()?'Desktop testing can use file upload':'Attach photo when prompted');setFieldReadinessStatus('mobile-mbtiles-status',mbtilesStatus.status);setMbtilesGuidance(mbtilesStatus.guidance);updateCollectorGeofenceStatus();if(!navigator.permissions?.query){setFieldReadinessStatus('mobile-permission-status',hasGps?'Location active in browser':'Grant location access when prompted');return}try{const result=await navigator.permissions.query({name:'geolocation'});const statusMap={granted:'Granted',prompt:'Needs prompt',denied:'Denied'};setFieldReadinessStatus('mobile-permission-status',statusMap[result.state]||'Checking...');result.onchange=()=>refreshFieldReadinessStatus().catch?.(()=>{})}catch{setFieldReadinessStatus('mobile-permission-status',hasGps?'Location active in browser':'Grant location access when prompted')}}
function keepCollectorFormVisibleAfterDraw(message='Field shape ready. Add the record details, then save this visit.'){try{mobilePostDrawRevealUntil=Date.now()+2200;window.CropCollectorApp?.state?.set?.('mobilePostDrawRevealUntil',mobilePostDrawRevealUntil)}catch{}setMapWorkflowBanner('selected','Shape selected',message);updateMobileSaveFlowState();refreshFieldReadinessStatus().catch?.(()=>{});try{showCollectorFeedback(message,'success')}catch{}if(window.innerWidth<900){try{setMobileWorkspace('collect')}catch{}requestAnimationFrame(()=>{try{scrollCollectorPrimaryActionIntoView()}catch{}try{focusCollectorSaveActions()}catch{}try{focusCollectorFormField('basic')}catch{}})}}
function initMap(){map=L.map('map',{center:[-19.0154,29.1549],zoom:6,minZoom:3,maxZoom:20,preferCanvas:true,zoomAnimation:!useTouchComfortMode(),fadeAnimation:!useTouchComfortMode(),markerZoomAnimation:!useTouchComfortMode(),bounceAtZoomLimits:false});const basemaps={osm:L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap contributors',maxZoom:20,maxNativeZoom:19}),satellite:L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{attribution:'Tiles &copy; Esri',maxZoom:20}),terrain:L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',{attribution:'OpenTopoMap',maxZoom:20,maxNativeZoom:17}),google_hybrid:L.tileLayer('https://mt1.google.com/vt/lyrs=y&x={x}&y={y}&z={z}',{attribution:'Google Hybrid',maxZoom:20,errorTileUrl:'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw=='})};const suppressGoogleErrorHandler=function(e){const url=e?.tile?.src||'';if(url.includes('mt1.google.com')||url.includes('mt2.google.com')||url.includes('mt3.google.com')){e.preventDefault?.();return false}};/* Tile errors are handled per basemap layer by attachBasemapRescue(). */window.__basemaps=basemaps;currentBasemap=basemaps.osm;currentBasemap.addTo(map);const basemapSelector=document.getElementById('basemap-selector');if(basemapSelector)basemapSelector.value='osm';attachBasemapRescue(currentBasemap,'osm');drawnItems=new L.FeatureGroup();map.addLayer(drawnItems);updateDrawMode();applyMapInteractionLock(false);document.getElementById('basemap-selector').onchange=e=>switchBasemap(e.target.value);map.on('click',()=>{if(window.innerWidth<900){if(Date.now()<=mobilePostDrawRevealUntil)return;toggleSidebar(false)}});map.on(L.Draw.Event.DRAWSTART,e=>{const kind=String(e.layerType||'polygon');if(isMobileCollector())setMobileWorkspace('map');setMapWorkflowBanner(kind==='marker'?'drawingPoint':'drawingPolygon')});map.on(L.Draw.Event.DRAWSTOP,()=>{if(!selectedPolygon)setMapWorkflowBanner('idle')});map.on(L.Draw.Event.EDITSTART,()=>setMapWorkflowBanner('editing'));map.on(L.Draw.Event.EDITSTOP,()=>setMapWorkflowBanner(selectedPolygon?'selected':'idle'));map.on(L.Draw.Event.CREATED,e=>{const layer=e.layer;drawnItems.addLayer(layer);attachLayer(layer);selectPolygon(layer);document.getElementById('capture-type').value=isPointLayer(layer)?'point':'polygon';if(editingEntryId){editGeometryReplaced=true;updateGeometryEditStatus('Replacement geometry selected. Update Entry will save this new shape.')}const drawPrompt=isPointLayer(layer)?'Point ready. Add the record details, then save this visit.':'Field shape ready. Add the record details, then save this visit.';keepCollectorFormVisibleAfterDraw(drawPrompt)});requestAnimationFrame(()=>map.invalidateSize());setMapWorkflowBanner('idle');refreshFieldReadinessStatus().catch?.(()=>{});if(isMobileCollector())setTimeout(()=>autoLocateCollector({silent:true}),700)}
function attachBasemapRescue(layer,key){if(!layer||layer.__collectorRescueBound)return;layer.__collectorRescueBound=true;let errors=0;layer.on('tileload',()=>{errors=0});layer.on('tileerror',()=>{errors+=1;if(errors>=4&&currentBasemap===layer&&key==='google_hybrid'&&window.__basemaps?.osm){const selector=document.getElementById('basemap-selector');if(selector)selector.value='osm';switchBasemap('osm');updateOfflineStatus('Google Hybrid tiles did not load, so the app switched to OpenStreetMap. You can still draw and save records.');showCollectorFeedback?.('Basemap switched to OpenStreetMap because Google Hybrid did not load.','warning')}})}
function switchBasemap(key){if(currentBasemap)map.removeLayer(currentBasemap);const requested=key==='mbtiles'&&mbtilesLayer?mbtilesLayer:window.__basemaps[key]||window.__basemaps.osm;currentBasemap=requested;attachBasemapRescue(currentBasemap,key);currentBasemap.addTo(map);requestAnimationFrame(()=>{try{map.invalidateSize(true)}catch{}})}
function attachLayer(layer){layer.on('click',()=>selectPolygon(layer));layer.on('touchstart',()=>selectPolygon(layer));if(layer.getElement){const element=layer.getElement();if(element)element.style.cursor='pointer'}}
function formatCoordinate(value){return Number(value).toFixed(6)}
function geometryLocationText(layer){if(isPointLayer(layer)){const latlng=layer.getLatLng();return `Point (${formatCoordinate(latlng.lat)}, ${formatCoordinate(latlng.lng)})`}const latlngs=layer.getLatLngs();const ring=Array.isArray(latlngs[0])?latlngs[0]:latlngs;const bounds=layer.getBounds();const center=bounds.getCenter();return `Polygon center (${formatCoordinate(center.lat)}, ${formatCoordinate(center.lng)})`}
function autofillLocation(layer){const input=document.getElementById('location-name');if(input&&!input.dataset.manualOverride){input.value=geometryLocationText(layer)}}
function setPhotoAttachment(name,dataUrl){const nameInput=document.getElementById('photo-name'),dataInput=document.getElementById('photo-data'),panel=document.getElementById('photo-preview-panel'),image=document.getElementById('photo-preview-image'),label=document.getElementById('photo-preview-name'),clearBtn=document.getElementById('clear-photo-btn');if(nameInput)nameInput.value=name||'';if(dataInput)dataInput.value=dataUrl||'';if(panel)panel.style.display=dataUrl?'block':'none';if(image)image.src=dataUrl||'';if(label)label.textContent=name?`Attached photo: ${name}`:'No photo attached';if(clearBtn)clearBtn.style.display=dataUrl?'flex':'none';feather.replace()}
function clearPhotoAttachment(){setPhotoAttachment('','')}
function readFileAsDataURL(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result||''));reader.onerror=()=>reject(new Error('Could not read that photo file.'));reader.readAsDataURL(file)})}
function loadImageFromDataURL(dataUrl){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('Could not process that photo.'));image.src=dataUrl})}
async function compressFieldPhoto(file){const original=await readFileAsDataURL(file);const image=await loadImageFromDataURL(original);const maxSide=1280;const scale=Math.min(1,maxSide/Math.max(image.width||maxSide,image.height||maxSide));const width=Math.max(1,Math.round((image.width||maxSide)*scale));const height=Math.max(1,Math.round((image.height||maxSide)*scale));const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const context=canvas.getContext('2d');if(!context)return original;context.drawImage(image,0,0,width,height);const jpeg=canvas.toDataURL('image/jpeg',0.72);return jpeg.length<original.length?jpeg:original}
function promptPhotoEvidenceRequired(){setCollectDetailStep('more');const drawer=document.getElementById('collect-observation-drawer');if(drawer)drawer.open=true;const pickBtn=document.getElementById('photo-pick-btn');pickBtn?.scrollIntoView({behavior:'smooth',block:'center'});pickBtn?.focus();setFieldReadinessStatus('mobile-photo-status','Photo required for this crop save');feather.replace();showCollectorFeedback('Attach a field photo before saving this record. On mobile you can use the camera, and on desktop you can choose an image file.','warning',{sticky:true})}
async function handlePhotoFile(file){if(!file)return;if(!file.type||!file.type.startsWith('image/'))return showCollectorFeedback('Choose an image file for field photo evidence.','warning');try{const dataUrl=await compressFieldPhoto(file);setPhotoAttachment(file.name.replace(/\s+/g,'_'),dataUrl);setFieldReadinessStatus('mobile-photo-status',`Attached: ${file.name}`);updateOfflineStatus(`Photo attached: ${file.name}`);showCollectorFeedback(`Photo attached: ${file.name}`,'success')}catch(error){showCollectorFeedback(error.message||'Could not attach that photo.','error',{sticky:true})}}
function createCurrentLocationPoint(lat,lng){showCurrentLocationOnMap(lat,lng,0,{center:true});syncLocationFieldFromCurrentPosition()}
function requestCurrentLocation(){if(!navigator.geolocation){setFieldReadinessStatus('mobile-permission-status','Location not supported');return showCollectorFeedback('This browser does not support GPS location.','error',{sticky:true})}setFieldReadinessStatus('mobile-permission-status','Requesting location permission');autoLocateCollector({forceCenter:true,silent:false})}
function getCurrentLocationGeometry(){if(!currentLocationLatLng)return null;return{type:'Point',coordinates:[Number(currentLocationLatLng.lng),Number(currentLocationLatLng.lat)]}}
function pointInLatLngRing(latlng,ring){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const xi=ring[i].lng,yi=ring[i].lat,xj=ring[j].lng,yj=ring[j].lat;const intersect=((yi>latlng.lat)!==(yj>latlng.lat))&&(latlng.lng<(xj-xi)*(latlng.lat-yi)/(yj-yi||1e-12)+xi);if(intersect)inside=!inside}return inside}
function validateCollectorGeofence(geometry,bufferMeters=10){if(!geometry||!currentLocationLatLng)return{ok:true,skipped:true,state:'gps-skipped',message:'GPS unavailable; geofence check skipped.'};const pos=currentLocationLatLng;if(geometry.type==='Point'){const[lng,lat]=geometry.coordinates;const dist=pos.distanceTo(L.latLng(lat,lng));return dist<=bufferMeters?{ok:true,distance:dist,state:dist<=1?'inside-field':'near-boundary',message:dist<=1?'Inside field':`Near boundary (${Math.round(dist)} m)`}:{ok:false,distance:dist,state:'outside-field',message:`GPS is ${Math.round(dist)} m from the field point (max ${bufferMeters} m). Move closer before saving.`}}if(geometry.type==='Polygon'&&geometry.coordinates?.[0]?.length){const ring=geometry.coordinates[0].map(([lng,lat])=>L.latLng(lat,lng));if(pointInLatLngRing(pos,ring))return{ok:true,state:'inside-field',message:'Inside field'};let minDist=Infinity;ring.forEach(ll=>{minDist=Math.min(minDist,pos.distanceTo(ll))});if(minDist<=bufferMeters)return{ok:true,distance:minDist,state:'near-boundary',message:`Near boundary (${Math.round(minDist)} m)`};return{ok:false,distance:minDist,state:'outside-field',message:`GPS is outside the field boundary (nearest edge ~${Math.round(minDist)} m). Stand inside the field or within ${bufferMeters} m of the edge.`}}return{ok:true,state:'inside-field',message:'Inside field'}}
function requestCurrentLocationFix(){return new Promise((resolve,reject)=>{if(!navigator.geolocation){setFieldReadinessStatus('mobile-permission-status','Location not supported');return reject(new Error('This browser does not support GPS location.'))}setFieldReadinessStatus('mobile-permission-status','Requesting location permission');navigator.geolocation.getCurrentPosition(position=>{const {latitude,longitude,accuracy}=position.coords;window.__collectorCurrentLocationAccuracyMeters=accuracy||null;showCurrentLocationOnMap(latitude,longitude,accuracy,{center:true});syncLocationFieldFromCurrentPosition();updateOfflineStatus(`GPS ready. Current location captured with approximately ${Math.round(accuracy||0)}m accuracy.`);refreshFieldReadinessStatus().catch?.(()=>{});resolve(L.latLng(latitude,longitude))},error=>{setFieldReadinessStatus('mobile-permission-status',error.code===1?'Denied':'Needs prompt');setFieldReadinessStatus('mobile-gps-status','Unavailable');reject(new Error(error.message||'Could not get current location.'))},{enableHighAccuracy:true,timeout:15000,maximumAge:0})})}
function setActiveDrawButtons(mode){}
function getPolygonDrawOptions(){const mobile=isMobileCollector();return{allowIntersection:mobile,showArea:true,shapeOptions:{color:'#2e7d32',weight:useTouchComfortMode()?5:3},drawError:{color:'#b00b00',timeout:2200,message:'Keep tracing around the outside of the field. If the line folds back over itself, finish the shape and adjust it in Edit mode.'}}}
function startDrawing(type){if(!map)return;if(window.innerWidth<900)setMobileWorkspace('map');try{map.invalidateSize(true)}catch{}const shapeOptions={color:'#2e7d32',weight:useTouchComfortMode()?5:3};let drawer;if(type==='point')drawer=new L.Draw.Marker(map);else if(type==='rectangle')drawer=new L.Draw.Rectangle(map,{shapeOptions});else drawer=new L.Draw.Polygon(map,getPolygonDrawOptions());setMapWorkflowBanner(type==='point'?'drawingPoint':'drawingPolygon');requestAnimationFrame(()=>{try{map.invalidateSize(true)}catch{}drawer.enable()});if(isMobileCollector())updateOfflineStatus(type==='rectangle'?'Rectangle mode is ready. Drag across the field area to create a boundary.':'Mobile polygon mode is ready. Tap around the outside of the field, then tap the first point to finish.')}
function updateDrawMode(){if(!map)return;if(!drawnItems||!(drawnItems instanceof L.FeatureGroup)){drawnItems=new L.FeatureGroup();}if(!map.hasLayer(drawnItems))map.addLayer(drawnItems);if(drawControl)map.removeControl(drawControl);const cropMode=activeCollectorPrimaryModule!=='livestock';drawControl=new L.Control.Draw({draw:cropMode?{polygon:getPolygonDrawOptions(),rectangle:{shapeOptions:{color:'#2e7d32',weight:useTouchComfortMode()?5:3}},polyline:false,circle:false,marker:true,circlemarker:false}:{polygon:false,rectangle:false,polyline:false,circle:false,marker:false,circlemarker:false},edit:{featureGroup:drawnItems}});map.addControl(drawControl);document.getElementById('offline-status').textContent=cropMode?(isMobileCollector()?'Use the map toolbar to add a point, polygon, or rectangle. Mobile polygon drawing now accepts touch-crossed shapes and cleans them before save.':'Use the map toolbar to add a point, polygon, or rectangle, then save the field details.'):'Livestock survey selected. No polygon or point capture is required for this path.';setMapWorkflowBanner(cropMode?(selectedPolygon?'selected':'idle'):'idle',cropMode?'':'Livestock survey',cropMode?'':'No map capture is needed here. Continue through the questionnaire pages and submit when complete.');updateMobileSaveFlowState();refreshFieldReadinessStatus().catch?.(()=>{})}
function updateGeometryEditStatus(message=''){const note=document.getElementById('geometry-edit-status');if(!note)return;if(!editingEntryId){note.style.display='none';note.textContent='';updateMobileSaveFlowState();return}note.style.display='block';note.textContent=message||(editGeometryReplaced?'Replacement geometry selected. Update Entry will save the new shape.':'Editing existing geometry. If you do not redraw, the current saved shape will be kept.');setMapWorkflowBanner('editing','Editing saved shape',note.textContent);updateMobileSaveFlowState()}
function isPersistedLayer(layer){const props=layer?.feature?.properties||{};return !!(props.entryId||props.localId)}
function updateRemoveShapeButton(){const removeBtn=document.getElementById('remove-shape-btn');if(!removeBtn)return;const canRemove=!!selectedPolygon&&!isPersistedLayer(selectedPolygon);removeBtn.style.display=canRemove?'flex':'none';removeBtn.disabled=!canRemove}
function removeSelectedShape(){if(!selectedPolygon)return showCollectorFeedback('Select the mistaken point or polygon first.','warning');if(isPersistedLayer(selectedPolygon))return showCollectorFeedback('Only unsaved drawing mistakes can be removed here. Saved records should be edited or archived instead.','warning',{sticky:true});const layerToRemove=selectedPolygon;drawnItems.removeLayer(layerToRemove);selectedPolygon=null;const locationInput=document.getElementById('location-name');if(locationInput&&!editingEntryId){locationInput.value='';delete locationInput.dataset.manualOverride}document.getElementById('save-entry-btn').style.display='none';document.getElementById('select-polygon-btn').style.display='flex';setSaveNextPlotButtonVisibility(false);if(editingEntryId&&editGeometryReplaced){editGeometryReplaced=false;updateGeometryEditStatus('Replacement geometry removed. Existing saved shape will be kept.');if(selectedEntryId)focusEntry(selectedEntryId)}else{updateOfflineStatus('Mistaken drawing removed. Draw again on the map when ready.');showCollectorFeedback('Mistaken drawing removed. Draw again on the map when ready.','info');setMapWorkflowBanner('cleanup')}updateRemoveShapeButton();updateMobileSaveFlowState();refreshFieldReadinessStatus().catch?.(()=>{});feather.replace()}
function selectPolygon(layer){const activeMode=getActiveMode();const entryId=layer?.feature?.properties?.entryId||layer?.feature?.properties?.localId||null;const linkedEntry=entryId?fieldEntries.find(item=>String(item.id)===String(entryId)||String(item.localId)===String(entryId)):null;if(activeMode==='validate'){if(!linkedEntry||linkedEntry.source!=='backend'){selectedEntryId=null;updateValidationTarget();setValidationSelectionMessage('Only synced server records can be selected for validation.','warning');return}if(!matchesValidationGeometry(linkedEntry)){selectedEntryId=null;updateValidationTarget();setValidationSelectionMessage(`Validation is filtered to ${getValidationGeometryLabel().toLowerCase()}. Select a matching feature.`,'warning');return}}if(selectedPolygon&&selectedPolygon!==layer&&selectedPolygon.setStyle)selectedPolygon.setStyle(getUnselectedFeatureStyle());selectedPolygon=layer;if(selectedPolygon.setStyle)selectedPolygon.setStyle(getSelectedFeatureStyle());document.getElementById('capture-type').value=isPointLayer(layer)?'point':'polygon';autofillLocation(layer);document.getElementById('save-entry-btn').style.display='flex';document.getElementById('select-polygon-btn').style.display='none';setSaveNextPlotButtonVisibility(true);setMapWorkflowBanner(editingEntryId?'editing':'selected');updateMobileSaveFlowState();refreshFieldReadinessStatus().catch?.(()=>{});const activeStepKey=getCollectorQuestionFlow(activeCollectorPrimaryModule)[currentCollectorWizardStep]||'';if(activeCollectorPrimaryModule==='crop'&&activeStepKey==='collector-draw-section'&&!editingEntryId)setCollectorWizardStep(currentCollectorWizardStep+1);if(activeMode==='validate'&&entryId){selectedEntryId=entryId;setValidationSelectionMessage(`${linkedEntry?.captureType||inferCaptureType(linkedEntry?.geometry)||'Feature'} selected for validation.`, 'info')}updateRemoveShapeButton();updateValidationTarget();if(window.innerWidth<900){setMobileWorkspace('collect');scrollCollectorPrimaryActionIntoView();focusCollectorSaveActions();requestAnimationFrame(()=>focusCollectorFormField('basic'))}}

function ensureMbtilesInput(){let input=document.getElementById('mbtiles-file');const offlineSection=document.getElementById('offline-status')?.closest('.section')||document.getElementById('sidebar');if(!input){if(!offlineSection)return null;input=document.createElement('input');input.type='file';input.id='mbtiles-file';offlineSection.appendChild(input)}input.type='file';input.accept='.mbtiles,.sqlite,.db,application/octet-stream';input.removeAttribute('hidden');input.style.display='block';input.style.position='fixed';input.style.left='-10000px';input.style.top='0';input.style.width='1px';input.style.height='1px';input.style.opacity='0.001';input.style.pointerEvents='auto';return input}
function bindMbtilesInput(inputOverride=null){const input=inputOverride||ensureMbtilesInput();if(!input||input.dataset.bound==='true')return input;input.accept='.mbtiles,.sqlite,.db,application/octet-stream';input.dataset.bound='true';input.addEventListener('change',async e=>{const file=e.target.files?.[0];if(file)await loadMBTiles(file);e.target.value=''});return input}
async function ensureSqlJsReady(){if(SQLRef)return SQLRef;let loader=window.initSqlJs;if(!loader){for(const candidate of SQLJS_CANDIDATES){try{await new Promise((resolve,reject)=>{const existing=[...document.scripts].find(script=>String(script.src||'').includes(candidate.script));if(existing){if(window.initSqlJs)return resolve();const finish=()=>window.initSqlJs?resolve():reject(new Error('SQL.js loaded but initSqlJs is unavailable'));existing.addEventListener('load',finish,{once:true});existing.addEventListener('error',()=>reject(new Error('Could not load SQL.js library')),{once:true});setTimeout(finish,150);return}const script=document.createElement('script');script.src=candidate.script;script.onload=()=>window.initSqlJs?resolve():reject(new Error('SQL.js loaded but initSqlJs is unavailable'));script.onerror=()=>reject(new Error('Could not load SQL.js library'));document.head.appendChild(script)});if(window.initSqlJs){loader=window.initSqlJs;break}}catch{}}}if(!loader)throw new Error('SQL.js library is unavailable. Reload the app or check the local vendor files to enable MBTiles loading.');let lastError=null;for(const candidate of SQLJS_CANDIDATES){try{SQLRef=await loader({locateFile:file=>`${candidate.wasmBase}${file}`});return SQLRef}catch(error){lastError=error}}throw new Error(lastError?.message||'Could not initialize SQL.js')}
function renderMbtilesDebugStatus(){const panel=document.getElementById('mbtiles-debug-status');if(!panel)return;const dbg=window.__lastMBTilesDebug||null;if(!dbg||!dbg.stage){panel.hidden=true;panel.innerHTML='';return}const metadata=dbg.metadata&&typeof dbg.metadata==='object'?dbg.metadata:{};const parts=[`<strong>Offline basemap details</strong>`,`<div>Stage: ${dbg.stage}</div>`];if(dbg.fileName)parts.push(`<div>File: ${dbg.fileName}</div>`);if(Number.isFinite(dbg.size))parts.push(`<div>Size: ${dbg.size} bytes</div>`);if(dbg.message)parts.push(`<div>Message: ${dbg.message}</div>`);if(metadata.name)parts.push(`<div>Name: ${metadata.name}</div>`);if(metadata.minzoom!==undefined||metadata.maxzoom!==undefined)parts.push(`<div>Zoom: ${metadata.minzoom??'?'}-${metadata.maxzoom??'?'}</div>`);if(metadata.bounds)parts.push(`<div>Bounds: ${metadata.bounds}</div>`);if(metadata.format)parts.push(`<div>Format: ${metadata.format}</div>`);panel.hidden=false;panel.innerHTML=parts.join('')}
function openMBTilesPicker(){const input=bindMbtilesInput(ensureMbtilesInput());if(!input){showCollectorFeedback('Could not find the offline tools area for MBTiles upload.','error',{sticky:true});return}input.value='';window.__lastMBTilesDebug={stage:'picker-open',message:'Waiting for file selection'};renderMbtilesDebugStatus();refreshFieldReadinessStatus().catch?.(()=>{});updateOfflineStatus('Choose an .mbtiles, .sqlite, or .db basemap file from your device.');try{if(typeof input.showPicker==='function')input.showPicker();else input.click()}catch{input.click()}}
function clearMBTiles(){if(mbtilesLayer&&map.hasLayer(mbtilesLayer))map.removeLayer(mbtilesLayer);mbtilesLayer=null;mbtilesDb=null;window.__lastMBTilesDebug=null;renderMbtilesDebugStatus();const o=document.querySelector('#basemap-selector option[value="mbtiles"]');if(o)o.remove();document.getElementById('basemap-selector').value='osm';switchBasemap('osm');refreshFieldReadinessStatus().catch?.(()=>{});document.getElementById('offline-status').textContent='MBTiles basemap cleared. Reload a file before going offline again.'}
function queryMB(sql,params=[]){if(!mbtilesDb)return null;const stmt=mbtilesDb.prepare(sql);try{stmt.bind(params);if(!stmt.step())return null;const row=stmt.getAsObject();const values=Object.values(row);return values.length?values[0]:null}finally{stmt.free()}}
function queryMBRow(sql,params=[]){if(!mbtilesDb)return null;const stmt=mbtilesDb.prepare(sql);try{stmt.bind(params);return stmt.step()?stmt.getAsObject():null}finally{stmt.free()}}
function tableExists(tableName){return !!queryMB("SELECT name FROM sqlite_master WHERE type = 'table' AND name = ?",[tableName])}
function getMBTilesMetadata(){if(!tableExists('metadata'))return{};const stmt=mbtilesDb.prepare("SELECT name, value FROM metadata");const metadata={};try{while(stmt.step()){const row=stmt.getAsObject();metadata[String(row.name||'').toLowerCase()]=row.value}}finally{stmt.free()}return metadata}
function parseMBTilesBounds(boundsValue){if(!boundsValue)return null;const parts=String(boundsValue).split(',').map(part=>Number(part.trim()));if(parts.length!==4||parts.some(value=>!Number.isFinite(value)))return null;const [west,south,east,north]=parts;return L.latLngBounds([south,west],[north,east])}
function normalizeMBTilesFormat(format){const token=String(format||'png').trim().toLowerCase();if(token==='jpg')return'image/jpeg';if(token==='jpeg')return'image/jpeg';if(token==='webp')return'image/webp';return'image/png'}
function getTileData(db,z,x,y){const rowModes=[(1<<z)-1-y,y];for(const rowY of rowModes){const stmt=db.prepare('SELECT tile_data FROM tiles WHERE zoom_level = ? AND tile_column = ? AND tile_row = ? LIMIT 1');try{stmt.bind([z,x,rowY]);if(stmt.step()){const row=stmt.getAsObject();if(row.tile_data)return row.tile_data}}finally{stmt.free()}}return null}
function describeMBTiles(metadata,fileName){const name=metadata.name||fileName;const minzoom=metadata.minzoom??'?';const maxzoom=metadata.maxzoom??'?';return`${name} (zoom ${minzoom}-${maxzoom})`}
async function loadMBTiles(file){try{window.__lastMBTilesDebug={stage:'file-selected',fileName:file?.name||'',size:file?.size||0};renderMbtilesDebugStatus();refreshFieldReadinessStatus().catch?.(()=>{});document.getElementById('offline-status').textContent=`Loading MBTiles: ${file.name}`;await ensureSqlJsReady();window.__lastMBTilesDebug={...window.__lastMBTilesDebug,stage:'sqljs-ready'};renderMbtilesDebugStatus();refreshFieldReadinessStatus().catch?.(()=>{});const buf=await file.arrayBuffer();window.__lastMBTilesDebug={...window.__lastMBTilesDebug,stage:'file-buffered'};renderMbtilesDebugStatus();const nextDb=new SQLRef.Database(new Uint8Array(buf));mbtilesDb=nextDb;window.__lastMBTilesDebug={...window.__lastMBTilesDebug,stage:'sqlite-opened'};renderMbtilesDebugStatus();if(!tableExists('tiles'))throw new Error('This file does not contain an MBTiles tiles table.');const metadata=getMBTilesMetadata();window.__lastMBTilesDebug={...window.__lastMBTilesDebug,stage:'metadata-read',metadata};renderMbtilesDebugStatus();const sampleTile=queryMBRow('SELECT zoom_level, tile_column, tile_row FROM tiles LIMIT 1');if(!sampleTile)throw new Error('This MBTiles file has no tiles to display.');const tileFormat=normalizeMBTilesFormat(metadata.format);const minZoom=Number(metadata.minzoom);const maxZoom=Number(metadata.maxzoom);mbtilesLayer=createMBTilesLayer(mbtilesDb,tileFormat,{minZoom:Number.isFinite(minZoom)?minZoom:0,maxZoom:Number.isFinite(maxZoom)?maxZoom:22});const existingOption=document.querySelector('#basemap-selector option[value="mbtiles"]');if(existingOption)existingOption.remove();const option=document.createElement('option');option.value='mbtiles';option.textContent=`MBTiles: ${metadata.name||file.name}`;document.getElementById('basemap-selector').appendChild(option);document.getElementById('basemap-selector').value='mbtiles';switchBasemap('mbtiles');const bounds=parseMBTilesBounds(metadata.bounds);if(bounds&&bounds.isValid())map.fitBounds(bounds,{padding:[20,20]});else if(Number.isFinite(maxZoom)&&map.getZoom()>maxZoom)map.setZoom(maxZoom);window.__lastMBTilesDebug={...window.__lastMBTilesDebug,stage:'loaded'};renderMbtilesDebugStatus();refreshFieldReadinessStatus().catch?.(()=>{});document.getElementById('offline-status').textContent=`Loaded MBTiles basemap: ${describeMBTiles(metadata,file.name)}. This basemap is ready for this browser session.`;showCollectorFeedback(`Loaded MBTiles basemap: ${describeMBTiles(metadata,file.name)}`,'success')}catch(e){mbtilesLayer=null;mbtilesDb=null;window.__lastMBTilesDebug={...window.__lastMBTilesDebug,stage:'error',message:e.message,stack:String(e.stack||'')};renderMbtilesDebugStatus();refreshFieldReadinessStatus().catch?.(()=>{});document.getElementById('offline-status').textContent=`Failed to load MBTiles: ${e.message}`;showCollectorFeedback(`Failed to load MBTiles: ${e.message}`,'error',{sticky:true})}}
function createMBTilesLayer(db,contentType,{minZoom=0,maxZoom=22}={}){const blank='data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==';return new(L.GridLayer.extend({options:{minZoom:0,maxZoom:22,maxNativeZoom:maxZoom,minNativeZoom:minZoom,noWrap:true,updateWhenIdle:true},createTile(coords,done){const tile=L.DomUtil.create('img','leaflet-tile');const size=this.getTileSize();tile.width=size.x;tile.height=size.y;tile.alt='';tile.setAttribute('role','presentation');tile.onload=()=>done(null,tile);tile.onerror=()=>{tile.src=blank;done(null,tile)};try{const source=getTileData(db,coords.z,coords.x,coords.y);if(source){const url=URL.createObjectURL(new Blob([source],{type:contentType}));tile.onload=()=>{URL.revokeObjectURL(url);done(null,tile)};tile.src=url}else tile.src=blank}catch{tile.src=blank}return tile}}))()}
window.__collectorOpenMbtilesPicker=function collectorOpenMbtilesPicker(){try{openMBTilesPicker();return false}catch(error){console.error('MBTiles picker open failed',error);try{showCollectorFeedback(`Could not open MBTiles picker: ${error.message||'Unknown error'}`,'error',{sticky:true,revealCollect:false})}catch{}return false}};
window.__collectorHandleMbtilesDirect=async function collectorHandleMbtilesDirect(input){try{const file=input?.files?.[0];if(!file)return false;await loadMBTiles(file);if(input)input.value='';return false}catch(error){console.error('Direct MBTiles load failed',error);try{showCollectorFeedback(`Failed to load MBTiles: ${error.message||'Unknown error'}`,'error',{sticky:true,revealCollect:false})}catch{}return false}};
window.CropCollectorApp?.registerModule('map',{
  initMap,
  updateDrawMode,
  startDrawing,
  selectPolygon,
  removeSelectedShape,
  requestCurrentLocation,
  getCurrentLocationGeometry,
  validateCollectorGeofence,
  openMBTilesPicker,
  loadMBTiles,
  clearMBTiles
});

window.refreshFieldReadinessStatus=refreshFieldReadinessStatus;
window.updateCollectorGeofenceStatus=updateCollectorGeofenceStatus;
window.__collectorCurrentLocationAccuracyMeters=window.__collectorCurrentLocationAccuracyMeters??null;
